export const careerInfo = [
  {
    id: 0,
    date: "Sept 2016 - Aug 2021",
    title: "University of Waterloo",
    icon: "School",
    subtitle: "Bachelors of Mathematics",
    chips: [],
  },
  {
    id: 1,
    date: "Jan 2020 - Apr 2020",
    title: "DevOps Engineer",
    icon: "Settings",
    subtitle: "OpenText",
    chips: ["k8s", "GCP", "Docker", "Helm", "Bash", "Python"],
  },
  {
    id: 2,
    date: "Sept 2020 - Dec 2020",
    title: "QA Automation Engineer",
    icon: "SmartToy",
    subtitle: "Imagine Communications",
    chips: ["Websockets", "RESTApi", "Postman", "Python"],
  },
  {
    id: 3,
    date: "Oct 2021 - Dec 2024",
    title: "Software Developer Engineer in Test",
    icon: "PrecisionManufacturing",
    subtitle: "Christie Digital Systems",
    chips: [
      "Flask",
      "Python",
      "Jenkins",
      "CI/CD",
      "Docker",
      "React",
      "Gitlab",
      "Ansible",
      "SQL",
      "Pytest",
    ],
  },
  {
    id: 4,
    date: "Dec 2024 - Present",
    title: "Software Developer Engineer in Test",
    icon: "ElectricCar",
    subtitle: "Ford Motors",
    chips: [
      "Groovy",
      "CI/CD",
      "Python",
      "Ansible",
      "Bash",
      "Powershell",
      "Click",
      "SQL",
    ],
  },
];
