name: Build and Deploy to Github Pages


on:
    workflow_dispatch:

permissions:
    contents: write
jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Node
              uses: actions/setup-node@v4
            
            - name: Install Dependencies
              working-directory: frontend/app/portfolio
              run: |
                npm i
            
            - name: Build and Deploy
              working-directory: frontend/app/portfolio
              run: |
                git config --global user.email "github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions[bot]"
                git remote set-url origin https://github-actions[bot]:${{ github.token }}@github.com/a9mansoo/portfolio.git
                echo "Building and deploying app"
                npm run deploy
