name: Build and Deploy to Github Pages


on:
    workflow_dispatch:
      inputs:
        skip_deploy:
          description: 'Skip deployment step'
          required: true
          type: boolean
          default: true

permissions:
    contents: write
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
          ARTIFACT_ID: ${{ steps.upload.outputs.artifact-id }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Setup Node
              uses: actions/setup-node@v4
            
            - name: Install Dependencies
              working-directory: frontend/app/portfolio
              run: |
                npm i
            
            - name: Build App
              working-directory: frontend/app/portfolio
              id: build
              run: |
                npm run build
                echo "dist_path=${GITHUB_WORKSPACE}/frontend/app/portfolio/dist" >> "$GITHUB_OUTPUT"
            
            - name: Upload Build Artifacts
              uses: actions/upload-artifact@v7
              id: upload
              with:
                name: app-${{ github.run_id }}
                path: ${{ steps.build.outputs.dist_path }}


    deploy:
        needs: build
        runs-on: ubuntu-latest
        if: ${{ !inputs.skip_deploy }}
        permissions:
          pages: write
          id-token: write
        environment:
          name: github-pages
          url: ${{ steps.deployment.outputs.page_url }}
        steps:  
            - name: Make dist dir
              run: mkdir dist
            - name: Download Build Artifacts
              uses: actions/download-artifact@v7
              with:
                artifact-ids: ${{ needs.build.outputs.ARTIFACT_ID }}
                digest-mismatch: error
                path: dist
            - name: Deploy
              uses: actions/deploy-pages@v4
              id: deployment
              with:
                artifact-name: dist
              